### ISSUE TITLE
Users cannot resubmit missed required fields

### ISSUE THREAD

**Issue by geshem** [buckii/gravity-forms-duplicate-prevention#10]
I had to disable the plugin, users who filled out the form and missed some required fields were then unable to resubmit after filling in those fields.

**Comment by paultela** [comment]
Can you point me to an example of where this is happening?  Any error messages or just the honeypot being triggered?  What are the field types of the required fields?  Versions of WordPress, Gravity Forms, and the plugin?  Any details you provide are helpful in investigating this. Thanks in advance.
