### ISSUE TITLE
[question] can be used on WP 4.3.1?

### ISSUE THREAD

**Issue by senlin** [buckii/gravity-forms-duplicate-prevention#4]
I just came across your plugin after searching for the same problem you describe this plugin solves. I noticed that it hasn't been updated for two years orso and am wondering if it still works and whether you still support it?

**Comment by BradGriffith** [comment]
We've tested on 4.0, but not 4.3.1 yet.  I would expect it to continue working, and we could probably put some time toward support if you run into issues.  Let us know what we can do to help!

**Comment by senlin** [comment]
Thanks for your answer, that is good to know. 

Perhaps an idea to update the plugin the the wordpress.org Repo? 
Compatible up to: 3.7.11 and Last Updated: 2013-11-29 doesn't give a lot of confidence. Also the readme.md file (here on github) can use an update :)
